export const ROLES = {
    SUPERADMIN: "SUPERADMIN",
    ADMIN: "ADMIN",
    TEACHER: "TEACHER",
    STUDENT: "STUDENT",
    ASSISTANT: "ASSISTANT",
};

export const ADMIN_ROLES = [ROLES.SUPERADMIN, ROLES.ADMIN];

export const ALL_AUTHENTICATED_ROLES = [
    ROLES.SUPERADMIN,
    ROLES.ADMIN,
    ROLES.TEACHER,
    ROLES.STUDENT,
    ROLES.ASSISTANT,
];
